<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="logo-brand">
    <a href="http://objectwave.com" title="Objectwave - Real World Solutions" target="_blank">
        <!--<img class="logo" src="<?php echo $block->getViewFileUrl('images/magento-logo.svg'); ?>" alt="Objectwave"/>-->
        <!--<img class="bkg-obwlogo" src="<?php echo $block->getViewFileUrl('images/bkg-obwlogo.png'); ?>" alt="obwstores"/>-->
    </a>
</div>